import { defineField, defineType } from "sanity";

export const homepage = defineType({
  name: "homepage",
  title: "Halaman Utama",
  type: "document",
  description: "Konten ini muncul di halaman utama saat website pertama kali dibuka. Setelah mengedit, klik Publish agar perubahan tampil di website.",
  fieldsets: [
    { name: "hero", title: "Hero - tampilan pertama halaman depan", options: { collapsible: true } },
    { name: "heroActions", title: "Tombol Hero", options: { collapsible: true } },
    { name: "sectionHeadings", title: "Judul section halaman utama", options: { collapsible: true, collapsed: true } },
  ],
  fields: [
    defineField({
      name: "heroEyebrow",
      title: "Label kecil di atas judul utama",
      description: "Muncul di bagian paling atas halaman utama, tepat di atas judul besar. Contoh: EVARCH.ID - ARCHITECTURE STUDIO.",
      type: "string",
      fieldset: "hero",
    }),
    defineField({
      name: "heroTitle",
      title: "Judul besar halaman utama",
      description: "Teks paling besar yang pertama dilihat pengunjung. Gunakan kalimat pendek, kuat, dan maksimal 2-3 baris.",
      type: "text",
      rows: 3,
      fieldset: "hero",
    }),
    defineField({
      name: "heroSubtitle",
      title: "Deskripsi pendek di bawah judul utama",
      description: "Muncul di bawah judul besar. Jelaskan layanan EVARCH secara singkat, idealnya 1-2 kalimat.",
      type: "text",
      rows: 3,
      fieldset: "hero",
    }),
    defineField({
      name: "heroImage",
      title: "Gambar utama halaman depan",
      description: "Gambar besar pertama yang terlihat saat website dibuka. Gunakan foto atau render arsitektur horizontal. Rekomendasi: 1920 x 1080 px atau rasio 16:9, ukuran file ideal di bawah 2-3 MB. Hindari gambar blur, terlalu gelap, atau terlalu kecil. Setelah mengedit, klik Publish agar tampil di website.",
      type: "image",
      options: { hotspot: true },
      fieldset: "hero",
    }),
    defineField({
      name: "primaryButtonLabel",
      title: "Teks tombol utama",
      description: "Tombol utama di Hero. Contoh: View Works. Gunakan 2-4 kata.",
      type: "string",
      fieldset: "heroActions",
    }),
    defineField({
      name: "primaryButtonLink",
      title: "Tujuan tombol utama",
      description: "Gunakan link section seperti #works atau URL lengkap bila mengarah ke halaman lain.",
      type: "string",
      fieldset: "heroActions",
    }),
    defineField({
      name: "secondaryButtonLabel",
      title: "Teks tombol kedua",
      description: "Tombol kedua di Hero, biasanya untuk verifikasi STRA. Gunakan teks singkat.",
      type: "string",
      fieldset: "heroActions",
    }),
    defineField({
      name: "secondaryButtonLink",
      title: "Tujuan tombol kedua",
      description: "Untuk STRA, gunakan link direktori resmi Dewan Arsitek Indonesia. Masukkan URL lengkap https://...",
      type: "string",
      fieldset: "heroActions",
    }),
    defineField({ name: "introTitle", title: "Judul pengantar (cadangan)", description: "Disiapkan untuk konten pengantar halaman utama. Saat ini tidak menjadi fokus tampilan utama.", type: "string", fieldset: "sectionHeadings" }),
    defineField({ name: "introText", title: "Teks pengantar (cadangan)", description: "Disiapkan untuk konten pengantar halaman utama. Gunakan maksimal 2 paragraf singkat.", type: "text", rows: 4, fieldset: "sectionHeadings" }),
    defineField({ name: "selectedWorksTitle", title: "Judul section Works", description: "Muncul di atas daftar proyek pada section Works di halaman utama.", type: "string", fieldset: "sectionHeadings" }),
    defineField({ name: "selectedWorksSubtitle", title: "Deskripsi section Works", description: "Teks pendukung di bawah judul Works. Jelaskan karakter portofolio secara singkat.", type: "text", rows: 3, fieldset: "sectionHeadings" }),
    defineField({ name: "studioTitle", title: "Judul section Studio", description: "Muncul pada section Studio di halaman utama.", type: "string", fieldset: "sectionHeadings" }),
    defineField({ name: "studioText", title: "Deskripsi section Studio", description: "Teks ringkas tentang cara kerja atau fokus studio. Idealnya 1-2 kalimat.", type: "text", rows: 4, fieldset: "sectionHeadings" }),
    defineField({ name: "expertiseTitle", title: "Judul section Expertise", description: "Muncul di atas daftar area keahlian EVARCH.", type: "string", fieldset: "sectionHeadings" }),
    defineField({ name: "expertiseSubtitle", title: "Deskripsi section Expertise", description: "Teks pendukung untuk menjelaskan layanan atau kapabilitas EVARCH.", type: "text", rows: 3, fieldset: "sectionHeadings" }),
    defineField({ name: "contactTitle", title: "Judul section Contact", description: "Muncul pada bagian kontak menjelang akhir halaman utama. Gunakan ajakan yang jelas dan hangat.", type: "string", fieldset: "sectionHeadings" }),
    defineField({ name: "contactSubtitle", title: "Deskripsi section Contact", description: "Teks pendek pendukung untuk ajakan konsultasi. Idealnya 1-2 kalimat.", type: "text", rows: 3, fieldset: "sectionHeadings" }),
  ],
  preview: { prepare: () => ({ title: "Halaman Utama" }) },
});
