import { defineField, defineType } from "sanity";
import { ClientImageInput } from "../components/ClientImageInput";

export const homepage = defineType({
  name: "homepage",
  title: "Halaman Utama",
  type: "document",
  description: "Konten ini muncul di halaman utama saat website pertama kali dibuka. Setelah mengedit, klik Publish agar perubahan tampil di website.",
  fieldsets: [
    { name: "hero", title: "Hero - Tampilan Pertama Website", options: { collapsible: true } },
    { name: "heroActions", title: "Tombol dan Link Hero", options: { collapsible: true } },
    { name: "sectionHeadings", title: "Judul Section yang Tampil di Website", options: { collapsible: true, collapsed: true } },
  ],
  fields: [
    defineField({
      name: "heroEyebrow",
      title: "Label kecil di atas judul utama",
      description: "Tampil di bagian paling atas Hero, tepat di atas judul besar. Contoh: EVARCH.ID - ARCHITECTURE STUDIO. Klik Publish setelah mengubahnya.",
      type: "string",
      fieldset: "hero",
    }),
    defineField({
      name: "heroTitle",
      title: "Judul besar halaman utama",
      description: "Teks paling besar yang pertama dilihat pengunjung. Gunakan kalimat pendek, kuat, dan maksimal 2-3 baris. Setelah mengubahnya, klik Publish.",
      type: "text",
      rows: 3,
      fieldset: "hero",
    }),
    defineField({
      name: "heroSubtitle",
      title: "Deskripsi pendek di bawah judul utama",
      description: "Tampil di bawah judul besar. Jelaskan layanan EVARCH secara singkat, idealnya 1-2 kalimat. Setelah mengubahnya, klik Publish.",
      type: "text",
      rows: 3,
      fieldset: "hero",
    }),
    defineField({
      name: "heroImage",
      title: "Gambar utama halaman depan",
      description: "Gambar ini muncul besar di bagian pertama halaman utama saat website dibuka. Jika ingin mengganti, upload gambar baru lalu klik Publish. Rekomendasi: landscape 16:9, minimal 1920px lebar, tidak blur.",
      type: "image",
      options: { hotspot: true },
      fields: [
        defineField({ name: "alt", title: "Alt text gambar", description: "Teks singkat untuk aksesibilitas dan SEO. Jelaskan isi gambar tanpa promosi, lalu klik Publish.", type: "string", validation: (rule) => rule.warning("Tambahkan alt text agar gambar lebih aksesibel.") }),
      ],
      components: { input: ClientImageInput },
      fieldset: "hero",
    }),
    defineField({
      name: "primaryButtonLabel",
      title: "Teks tombol utama",
      description: "Tombol utama di Hero untuk mengajak pengunjung menjelajahi website. Contoh: View Works. Gunakan 2-4 kata, lalu klik Publish.",
      type: "string",
      fieldset: "heroActions",
    }),
    defineField({
      name: "primaryButtonLink",
      title: "Tujuan tombol utama",
      description: "Tombol ini membawa pengunjung ke tujuan utama Hero. Gunakan anchor seperti #works atau URL lengkap bila mengarah ke halaman lain, lalu klik Publish.",
      type: "string",
      fieldset: "heroActions",
    }),
    defineField({
      name: "secondaryButtonLabel",
      title: "Teks tombol kedua",
      description: "Tombol kedua di Hero, biasanya untuk verifikasi STRA. Gunakan teks singkat, lalu klik Publish.",
      type: "string",
      fieldset: "heroActions",
    }),
    defineField({
      name: "secondaryButtonLink",
      title: "Tujuan tombol kedua",
      description: "Untuk STRA, gunakan link direktori resmi Dewan Arsitek Indonesia. Masukkan URL lengkap https://..., lalu klik Publish.",
      type: "string",
      fieldset: "heroActions",
    }),
    defineField({ name: "introTitle", title: "Judul pengantar (cadangan)", description: "Disiapkan untuk konten pengantar halaman utama. Saat ini tidak menjadi fokus tampilan utama.", type: "string", fieldset: "sectionHeadings" }),
    defineField({ name: "introText", title: "Teks pengantar (cadangan)", description: "Disiapkan untuk konten pengantar halaman utama. Gunakan maksimal 2 paragraf singkat.", type: "text", rows: 4, fieldset: "sectionHeadings" }),
    defineField({ name: "selectedWorksTitle", title: "Judul section Works", description: "Muncul di atas daftar proyek pada section Works di halaman utama. Gunakan judul singkat, lalu klik Publish.", type: "string", fieldset: "sectionHeadings" }),
    defineField({ name: "selectedWorksSubtitle", title: "Deskripsi section Works", description: "Teks pendukung di bawah judul Works. Jelaskan karakter portofolio secara singkat dalam 1-2 kalimat, lalu klik Publish.", type: "text", rows: 3, fieldset: "sectionHeadings" }),
    defineField({ name: "studioTitle", title: "Judul section Studio", description: "Muncul pada section Studio di halaman utama. Gunakan judul ringkas yang sesuai dengan narasi studio, lalu klik Publish.", type: "string", fieldset: "sectionHeadings" }),
    defineField({ name: "studioText", title: "Deskripsi section Studio", description: "Teks ringkas tentang cara kerja atau fokus studio. Idealnya 1-2 kalimat, lalu klik Publish.", type: "text", rows: 4, fieldset: "sectionHeadings" }),
    defineField({ name: "expertiseTitle", title: "Judul section Expertise", description: "Muncul di atas daftar area keahlian EVARCH. Gunakan judul jelas dan ringkas, lalu klik Publish.", type: "string", fieldset: "sectionHeadings" }),
    defineField({ name: "expertiseSubtitle", title: "Deskripsi section Expertise", description: "Teks pendukung untuk menjelaskan layanan atau kapabilitas EVARCH. Idealnya 1-2 kalimat, lalu klik Publish.", type: "text", rows: 3, fieldset: "sectionHeadings" }),
    defineField({ name: "contactTitle", title: "Judul section Contact", description: "Muncul pada bagian kontak menjelang akhir halaman utama. Gunakan ajakan yang jelas dan hangat, lalu klik Publish.", type: "string", fieldset: "sectionHeadings" }),
    defineField({ name: "contactSubtitle", title: "Deskripsi section Contact", description: "Teks pendek pendukung untuk ajakan konsultasi. Idealnya 1-2 kalimat, lalu klik Publish.", type: "text", rows: 3, fieldset: "sectionHeadings" }),
  ],
  preview: { prepare: () => ({ title: "Halaman Utama" }) },
});
